# Application Name
spring.application.name=students_courses

# H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:studentsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show SQL in logs
spring.jpa.show-sql=true

# Automatically create and destroy the schema based on entity definitions
spring.jpa.hibernate.ddl-auto=create-drop

# Data initialization settings - defer until after schema creation
spring.jpa.defer-datasource-initialization=true

# Enable H2 web console
spring.h2.console.enabled=true


